// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9FYf7a66GHdS9XT2jinbXG48Q2Ggf94',
    appId: '1:795265236796:web:1f6ab55e0969b9f440e839',
    messagingSenderId: '795265236796',
    projectId: 'dina-fb',
    authDomain: 'dina-fb.firebaseapp.com',
    databaseURL: 'https://dina-fb-default-rtdb.firebaseio.com',
    storageBucket: 'dina-fb.appspot.com',
    measurementId: 'G-C4K7ZJVZE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNf3pbzLfAMkR8eKVrX_7_TQG2N56BTwU',
    appId: '1:795265236796:android:e76a256be2cdbd4840e839',
    messagingSenderId: '795265236796',
    projectId: 'dina-fb',
    databaseURL: 'https://dina-fb-default-rtdb.firebaseio.com',
    storageBucket: 'dina-fb.appspot.com',
  );
}
